config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'polls#index'
  post '/vote' => 'polls#vote', as: :vote
  post '/ranking' => 'polls#ranking', as: :ranking
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/poll.rb
# frozen_string_literal: true

class Poll < ApplicationRecord
    has_many :poll_options

    def all_votes
        poll_options.sum(:votes)
    end
end

app/models/poll_option.rb
# frozen_string_literal: true

class PollOption < ApplicationRecord
  belongs_to :poll

  def percentage
    (votes.to_f / poll.all_votes.to_f * 100.0).round(2)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/polls_controller.rb
# frozen_string_literal: true

class PollsController < ApplicationController
  before_action :set_poll_options, only: %i[index ranking]

  def index; end

  def vote
    @poll_option = PollOption.find(params[:poll_option_id])
    @poll_option.increment!(:votes)

    respond_to do |format|
      format.turbo_stream { render :vote }
    end
  end

  def ranking
    @poll_options.order(:votes)

    respond_to do |format|
      format.turbo_stream { render :ranking }
    end
  end

  def set_poll_options
    @poll = Poll.where(finished_at: nil).last
    @poll_options = @poll.poll_options.order(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/polls_helper.rb
# frozen_string_literal: true

module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paredão das linguagens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 pb-12 max-w-xl">
      <%= yield %>
    </main>
  </body>
</html>

app/views/polls/_poll.html.erb
<div id="poll-container">
    <h1 class="text-4xl font-bold">
        Paredão das Linguagens: Vote para eliminar.
        <%= @poll_options.pluck(:name).to_sentence(last_word_connector: ' ou ') + '?' %>
    </h1>
    <div class="flex flex-col gap-4 w-100 mt-8">
        <% @poll_options.each do |item| %>
            <%= button_to(vote_url,
                          method: :post,
                          params: { poll_option_id: item.id },
                          class: 'flex-grow flex items-center border border-gray-600 text-left p-4',
                          form_class: 'w-100 flex') do
            %>
                <h2 class="text-2xl text-slate-800 font-bold flex-grow">
                    <%= item.name %>
                </h2>
                <%= image_tag(item.photo, class: 'w-16 h-16 object-contain') %>
            <% end %>
        <% end %>
        <%= button_to(ranking_url,
                        method: :post,
                        class: 'block text-center p-4 text-white bg-violet-800 hover:bg-violet-900 flex-grow',
                        form_class: 'w-100 flex flex-grow') do
        %>
            Ver ranking
        <% end %>

    </div>
</div> 

app/views/polls/index.html.erb
<%= render 'poll' %>

app/views/polls/ranking.turbo_stream.erb
<%= turbo_stream.replace 'poll-container' do %>
    <div id="poll-container">
        <h1 class="text-4xl font-bold">
            Porcentagens dos votos
        </h1>
        <div class="flex flex-col gap-4 w-100 mt-8">
            <% @poll_options.each do |item| %>
              <div class="flex-grow flex border border-gray-600 p-4 flex-col">
                <div class="flex flex-row flex-grow items-center text-left">
                    <h2 class="text-2xl text-slate-800 font-bold flex-grow">
                        <%= item.name %>
                    </h2>
                    <%= image_tag(item.photo, class: 'w-16 h-16 object-contain') %>
                </div>
                <div class="flex flex row flex grow">
                    <div class="flex flex-col flex-grow">
                        <div class="relative pt-1">
                            <div class="overflow-hidden h-2 mb-4 text-xs flex rounded bg-violet-200">
                                <div style="width: <%= item.percentage %>%" 
                                     class="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-violet-500">
                                </div>
                            </div>
                        </div>
                        <p class="mr-4 flex-grow italic"><%= item.percentage %>% -  <%= item.votes %> votos</p>
                    </div>
                </div>
              </div>
            <% end %>
            <%= link_to('Voltar',
                    root_path,
                    class: 'block text-center p-4 text-white bg-violet-800 hover:bg-violet-900')
            %>
        </div>
    </div> 
<% end %> 

app/views/polls/vote.turbo_stream.erb
<%= turbo_stream.replace 'poll-container' do %>
    <div id="poll-container">
        <div class="flex items-center p-4 mb-8">
            <div class="flex-grow">
                <p class="font-semibold text-slate-700">
                    Você votou em
                </p>
                <p class="text-2xl font-bold">
                    <%= @poll_option.name %>
                </p>
            </div>
            <%= image_tag(@poll_option.photo, class: 'w-16 h-16 object-contain') %>
        </div>
        <%= link_to('Votar novamente',
                    root_path,
                    class: 'block text-center p-4 text-white bg-violet-800 hover:bg-violet-900')
        %>
    </div>
<% end %> 